language: node_js
node_js:
  - 10
cache: npm
install:
  - npm install gitbook-cli -g
  - gitbook install
script:
  - gitbook build
deploy:
#Install and run Gitbook
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: _book
    on:
      branch: master